 
mybatis: 
#  typeAliasesPackage: com.chameleon
  mapperLocations: classpath:mapper/*.xml
spring: 
#  profiles: dev
  datasource:
    url:  
    username:  
    password:  
    driver-class-name: com.mysql.jdbc.Driver